# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c012afee53659cff81b347053ffecb401594dbf95d2bb15eba82f8f432cc1104f5a3e6f816d5ac7b8bab4a5d14655e786c422f19ae7a8fabd99560fc07c4745f

test:
  secret_key_base: 0712599ab18fd9d37a3b5ec18f057a110b2e3afc219cb6deae3205e22d96826e8e927959bc0fac85a2fa621f5a15a9a1d379c42f2b096832dcf3af0cf8540263

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
